feat:
  - head-branch: ['^feat', '^feature']
  - changed-files:
    - any-glob-to-any-file: ['src/**/*.ts']

fix:
  - head-branch: ['^fix', '^bug']

chore:
  - head-branch: ['^chore', '^refactor']
  - changed-files:
    - any-glob-to-any-file: ['.github/**', 'package.json', 'biome.json']

docs:
  - head-branch: ['^docs']
  - changed-files:
    - any-glob-to-any-file: ['**/*.md']

test:
  - head-branch: ['^test']
  - changed-files:
    - any-glob-to-any-file: ['test/**', '**/*.test.ts']
